config to control the behavior of the CallsMonitoring job
yeti-switch/yeti-web pull request #1527
Opened 2024-08-09 14:57 UTC by Ivanov-Anton

### Description

introduces new configuration options in yeti_web.yml to control the behavior of the CallsMonitoring job when dealing with disabled customer
authentication and termination gateways:

- calls_monitoring.teardown_on_disabled_customer_auth
- calls_monitoring.teardown_on_disabled_term_gw

The CallsMonitoring class has been updated to use
these configurations in the
relevant methods. If the configs are not present,
the current behavior (terminating
calls for disabled customer auth and termination
gateways) is maintained.

The calls_monitoring_spec.rb file has been updated with new test cases for the
introduced configurations.

2024-08-10 18:26 UTC, Ivanov-Anton commented on app/jobs/jobs/calls_monitoring.rb
> -    private
removed because duplicated.

2024-08-12 18:28 UTC, Ivanov-Anton commented
@dmitry-sinina this PR is ready to code review

2024-08-15 05:08 UTC, Ivanov-Anton commented
@dmitry-sinina this PR is ready to code review

2024-08-15 14:59 UTC, senid231 requested changes

2024-08-15 14:59 UTC, senid231 commented on app/jobs/jobs/calls_monitoring.rb
>      end
I think better would be to split `detect_gateway_calls_to_reject` into 2 methods: `detect_orig_gateway_calls_to_reject` and `detect_term_gateway_calls_to_reject` and use same approach that was used in `detect_customers_auth_calls_to_reject`

**P.S.** also please refactor adding calls to `@terminate_calls`, they all should use `terminate_calls` method

```ruby
    def detect_orig_gateway_calls_to_reject
      return unless teardown_enabled?(:teardown_on_disabled_orig_gw)

      calls_to_terminate = flatten_calls.select do |call|
        disabled_orig_gw_active_calls.key?(call[:orig_gw_id])
      end
      terminate_calls(calls_to_terminate)
    end

    def detect_term_gateway_calls_to_reject
      return unless teardown_enabled?(:teardown_on_disabled_term_gw)

      # same
    end

    def terminate_calls(calls)
      @terminate_calls.merge!(calls.index_by { |c| c[:local_tag] })
    end
```

2024-08-19 11:43 UTC, Ivanov-Anton commented
@senid231 appliyed your last suggestion.

2024-08-24 11:54 UTC, dmitry-sinina commented
new config variables should be described there:

https://github.com/yeti-switch/yeti-web/blob/master/config/initializers/_config.rb#L25

2024-09-03 15:19 UTC, Ivanov-Anton commented
just appliyed your last suggestion

2024-09-03 16:39 UTC, merged